config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :articles #,only: [:show, :index, :new, :create, :edit, :update, :destroy]
   resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 20}
    validates :description, presence: true, length: {minimum: 6, maximum: 100}
    belongs_to :user
    has_many :Comments
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :articles
        has_many :Comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show,:edit, :update ,:destroy]
    def show
    end
    def index
        @articles=Article.all
        # @articles.user_id
    end

    def new
        @article=Article.new
    end

    def create
        @article= Article.new(article_params)
        if @article.save
            flash[:noitce]="Article created"
            redirect_to @article
        else
            render 'new'
        end
    end

    def edit
    end

    def update
    
        if @article.update(article_params)
            flash[:notice]="Article Updated"
            redirect_to @article
        else
            flash[:notice]="No Alteration is being made"
            redirect_to 'edit'
        end

    end

    def destroy
        @article.destroy
        redirect_to articles_path
        flash[:notice]="Article deleted"
    end
    private
     def set_article
        @article = Article.find(params[:id])
     end
     def article_params
        params.require(:article).permit(:title,:description,:user_id)
     end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:show,:edit, :update ,:destroy]
    def show
    end
    def index
        @comments=Comment.all
    end

    def new
        @comment=Comment.new

    end

    def create
        @comment= Comment.new(comment_params)
        if @comment.save
            flash[:noitce]="Comment created"
            redirect_to @comment
        else
            render 'new'
        end
    end

    def edit
    end

    def update
    
        if @comment.update(comment_params)
            flash[:notice]="Comment Updated"
            redirect_to @comment
        else
            redirect_to 'edit'
        end

    end

    def destroy
        @comment.destroy
        redirect_to comments_path
        flash[:notice]="Comment deleted"
    end
    private
     def set_comment
        @comment = Comment.find(params[:id])
     end
     def comment_params
        params.require(:comment).permit(:comment,:user_id)
     end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

    <h2>Error while creating due to</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<div class="card">
  <div class="card-body">
        <%= form_with(model: @article, local: true) do |f|%>

            <p>
                <%=f.label :title%><br/>
                <%=f.text_field :title,class: "form-control"%>
            </p>

            <p>
                <%=f.label :description%><br/>
                <%=f.text_area :description,class: "form-control"%>
            </p>

             <p>
                <%=f.label :current_user%><br/>
                <%=f.text_area :user_id, id: :article_user_id,value: current_user.id, class: "form-control"%>
            </p>

            <p>
                <%=f.submit class:"btn btn-success"%>
            </p>

        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<div class="card">
    <div class="card-header">
        <h1>Editing a new article</h1>
    </div>
    <%=render 'form'%>
</div>
<br>
    <%=link_to 'Back',articles_path(@article),class:"btn btn-secondary"%>


app/views/articles/index.html.erb
<div class="card">
  <div class="card-header">
     <h1>Showing all articles available</h1>
  </div>
   <div class="card-body">
 
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th colspan="3">Actions</th>
                    <th> Author </th>
                </tr>
            </thead>

            <tbody>
                <%@articles.each do |article|%>
                
                <tr>
                    <%if article.user_id==current_user.id %>
                        <td><%=article.title%></td>
                        <td><%=article.description%></td>
                        <td><%=link_to 'Show',article_path(article),class:"btn btn-secondary"%></td>
                        <td><%=link_to 'Edit Article',edit_article_path(article),class:"btn btn-warning"%></td>
                        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure"},class:"btn btn-danger" %></td>
                        <td><%=current_user.email%></td>
                    <%end%>
                </tr>

                <%end%>
            </tbody>



        </table>
    </div>
</div>
<br >
<p>
     <%=link_to 'Create an Article',new_article_path, class:"btn btn-primary"%>
</p>

app/views/articles/new.html.erb
<div class="card-header">
    <h1>Creating a new article</h1>
</div>
<%=render 'form'%>
<br>
<p>
    <%=link_to 'Back',articles_path(@article),class:"btn btn-secondary"%>
</p>

app/views/articles/show.html.erb
<div class="card">
  <div class="card-header">
    <h1>Showing the articles</h1>
  </div>
<div class="card-body">
    <p><strong>Title: </strong><%=@article.title%></p>
    <p><strong>Description: </strong><%=@article.description%></p>


    <%=link_to 'Edit Article',edit_article_path(@article),class:"btn btn-warning"%> |
    <%=link_to 'Delete',article_path(@article), method: :delete,data: { confirm:"Are you sure"},class:"btn btn-danger" %> |
    <%=link_to 'Back',articles_path(@article),class:"btn btn-secondary"%>
</div>

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>

    <h2>Error while creating due to</h2>
    <ul>
        <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<div class="card">
  <div class="card-body">
        <%= form_with(model: @comment, local: true) do |f|%>
            <p>
                <%=f.label :comment%><br/>
                <%=f.text_area :comment,class: "form-control"%>
            </p>

             <p>
                <%=f.label :current_user%><br/>
                <%=f.text_area :user_id, id: :comment_user_id,value: current_user.id, class: "form-control"%>
            </p>

            <p>
                <%=f.submit class:"btn btn-success"%>
            </p>

        <% end %>
    </div>
</div>

app/views/comments/edit.html.erb
edit page
<div class="card">
    <div class="card-header">
        <h1>Editing a comment</h1>
    </div>
    <%=render 'form'%>
</div>
<br>
    <%=link_to 'Back',comments_path(@comment),class:"btn btn-secondary"%>

app/views/comments/index.html.erb
Comment Section
<div class="card">
  <div class="card-header">
     <h1>Showing comments of relative article available</h1>
  </div>
   <div class="card-body">
 
        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th colspan="3">Actions</th>
                    <th> Author </th>
                </tr>
            </thead>

            <tbody>
                <%@comments.each do |comment|%>
                
                <tr>
                    <%if comment.user_id==current_user.id %>
                        <td><%=comment.description%></td>
                        <td><%=link_to 'Show',comment_path(comment),class:"btn btn-secondary"%></td>
                        <td><%=link_to 'Edit comment',edit_comment_path(comment),class:"btn btn-warning"%></td>
                        <td><%= link_to 'Delete', comment_path(comment), method: :delete, data: {confirm: "Are you sure"},class:"btn btn-danger" %></td>
                        <td><%=current_user.email%></td>
                    <%end%>
                </tr>

                <%end%>
            </tbody>



        </table>
    </div>
</div>
<br >
<p>
     <%=link_to 'Post your comment ',new_comment_path, class:"btn btn-primary"%>
</p>

app/views/comments/new.html.erb
<div class="card-header">
    <h1>Post a new commment</h1>
</div>
<%=render 'form'%>
<br>
<p>
    <%=link_to 'Back',comment_path(@comment),class:"btn btn-secondary"%>
</p>

app/views/comments/show.html.erb
<div class="card">
  <div class="card-header">
    <h1>Showing the comments</h1>
  </div>
<div class="card-body">
    <p><strong>Description: </strong><%=@comment.comment%></p>


    <%=link_to 'Edit Comment',edit_comment_path(@comment),class:"btn btn-warning"%> |
    <%=link_to 'Delete',comment_path(@comment), method: :delete,data: { confirm:"Are you sure"},class:"btn btn-danger" %> |
    <%=link_to 'Back',comment_path(@comment),class:"btn btn-secondary"%>
</div>

app/views/home/index.html.erb
<h1>Welcome to Home Page</h1>

app/views/layouts/_messages.html.erb
    <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    <% flash.each do|name,msg|%>
          <%=msg%>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%# <ul class="nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Active</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul> %>
      <%=render 'layouts/messages'%>
      
      
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            You have Logged in as <strong><%= current_user.email %></strong>.
            <br />
            <%= link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-warning" %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-primary"  %>
          <%# <% else %>
            <%# <%= link_to "Sign up", new_user_registration_path %>
            <%# <%= link_to "Login", new_user_session_path %>
          <% end %>
    <%= yield %>
    

  </body>
</html>